# Generated by Django 5.0.2 on 2024-02-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('authors', models.CharField(max_length=100)),
                ('abstract', models.TextField()),
                ('panelist', models.CharField(max_length=100)),
                ('advisors', models.CharField(max_length=255)),
                ('defense_date', models.DateField()),
                ('published_date', models.DateField()),
                ('keywords', models.CharField(max_length=255)),
            ],
        ),
    ]
