# Generated by Django 5.0.2 on 2024-02-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_thesis_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='department',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thesis',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
