# Generated by Django 5.0.2 on 2024-03-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_thesis_options_alter_thesis_published_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, unique_for_date='published_date'),
        ),
    ]
